# This is a basic workflow to help you get started with Actions

name: test2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: ls
        run: ls -al

      # Runs a set of commands using the runners shell
      - name: echo
        run: echo "This is checkout"
        

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: chmod gradle    
        run: chmod +x ./gradlew
      
      - name: build       
        run: ./gradlew build --no-daemon
            
      - name : check build
        run : ls ./build/libs
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: docker ps
        run: docker ps
      
      - name : docker copy
        run : cp ./build/libs/*.war ./Dockerfile
          
      - name: docker build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat-github_v1 ./Dockerfile
          
      - name: check images    
        run: docker images
        
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: image push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat-github_v1
        

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'cluster-1'
          location: 'us-central1-c'

        
      - name: k8s rollout
        run: kubectl rollout restart deployment/was
        
      - id: 'auth-cs'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CS_KEY }}'


      
      - id: 'upload-files'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: ./build/libs/*.war
          destination: wayrkks-cloud
          parent: false


